### PR TITLE
Write termination message to TERMINATION_MESSAGE_PATH

### LINKED ISSUE #233: record termination message
When the PMEM-CSI driver encounters a fatal problem, it should write an explanation to the termination log file before quitting. That way, `kubectl describe pods` can show the reason why the container is no longer running.

One example is `Failed to run driver: FATAL: /sys mounted read-only, can not operate`.

### PR DESCRIPTION
**Pull request by okartau**
Write termination message to TERMINATION_MESSAGE_PATH
   
The path is different from default /dev/termination-log
because we need to pass /dev/ explicitly to containers,
and that is known to cause container creation failure
if combined with termination-log located on /dev.
So we relocate termination log to /tmp.
We define env.var that we pass into container so that
container knows where to create the termination message.

Resolves #233

### CODE REVIEW

**Comment by okartau** [comment]
This implement idea in #233. Seems terminationMessagePath can not use value from already defined env.var, so we have to spell the path out there.
In Kustomize part: with current version, I only get it added to one pod (node part), but not controller part. How to specify patch stmt to get it to both?

**Comment by okartau** [comment]
@pohly  can you comment on this: 
Connected to work in this PR, I want to add terminationMessagePath to more pods via kustomize.
But I am puzzled how this works. Currently the file 
deploy/kustomize/kubernetes-1.13-direct/direct-patch.yaml
specifies overlay that adds entries in 
deploy/kubernetes-1.13/pmem-csi-direct.yaml

The direct-patch.yaml says in comment:
`The PMEM-CSI driver must be in container #0`
and it uses "add" format  path: `/spec/template/spec/containers/0/`
i.e. selects `array element 0`

But the base file that is used:
deploy/kustomize/driver/pmem-csi.yaml

contains 2 container specs: 1st for controller, 2nd for node.
The patching code adds entries in the 2nd entry only.
How is this explained by the patch `addressing entry 0 `?  
And how to apply patch to 1st container in that file?
Did I understood wrong how the patching works?

My idea was, we should add terminationMessagePath to all driver containers,
so I want to patch both container entries in that file. But how to target the 1st entry then
if 2nd entry is targeted by index 0.

**Comment by pohly** [comment]
> The patching code adds entries in the 2nd entry only.
> How is this explained by the patch addressing entry 0 ?

It's explained by the `kustomization.yaml`:
```
patchesJson6902:
- target:
    group: apps
    version: v1beta2
    kind: DaemonSet
    name: pmem-csi-node
  path: direct-patch.yaml
```

That says that the patch is to be applied to the DaemonSet.

> And how to apply patch to 1st container in that file?

You need to add a second entry in the `patchesJson6902` array which references the `StatefulSet`.

> My idea was, we should add terminationMessagePath to all driver containers

This is starting to get complicated. Let's reconsider our assumptions: do we really need different `terminationMessagePath` settings for direct and LVM mode? I think both modes can put the termination message into `/tmp`, and then the change can go into `deploy/kustomize/driver/pmem-csi.yaml`.

**Comment by okartau** [comment]
> Let's reconsider our assumptions: do we really need different `terminationMessagePath` settings

That was my idea as well, to unify settings over all scenarios

**Comment by okartau** [comment]
If we agree to unify terminationPath in all driver variants (and that is a sane plan IMHO),
then we can stop patching that part using kustomize and write the settings to base config,
and the need to add patching rules drops away.
It makes base config bigger, but advantage is reduced patching part.
I force-pushed that solution.
It seems to work in brief test:
- Regular tests (deploy, e2e) pass.
- The termination message I tested by forcing error via incorrect -mode parameter.
I can see the error written in `kubectl describe pod`:
```
    Last State:     Terminated
      Reason:       Error
      Message:      Failed to initialize driver:Invalid driver mode: badmode
```
This was tested in Clear cluster in LVM mode.
Previously we had differences in explicit mounts (which originally caused the whole terminationPath change). Some of diffs have now been unified between different deploy scenarios,
so it makes sense to verify both modes, I will test direct mode next.

**Comment by okartau** [comment]
direct mode tests pass as well in Clear VM cluster

**Comment by okartau** [comment]
This is simpler/smaller than #263 so we can postpone and perform rebase after #263 gets merged

File: cmd/pmem-csi-driver/main.go [hunk 1]
```diff
@@ -66,12 +66,25 @@ func main() {
...
+	fmt.Println(str)
+	terminationlogpath := os.Getenv("TERMINATION_LOG_PATH")
+	if terminationlogpath == "" {
+		terminationlogpath = os.Getenv("/dev/termination-log")
+	}
+	f, err := os.Create(terminationlogpath)
+	if err == nil {
+		f.WriteString(str)
+		f.Close()
+	}
```
Comment (pohly) [inline cmd/pmem-csi-driver/main.go]: Using `ioutil.WriteFile` is simpler.

**Comment by pohly** [comment]
You need to rebase and re-run "make kustomize".

File: cmd/pmem-csi-driver/main.go (hunk 1 above)
Comment (okartau) [reply cmd/pmem-csi-driver/main.go]: I used os because it's already imported and operates on string, where ioutil.WriteFile needs new import and operates on byte[]. No big difference, we can indeed save few lines where we actually call it.

Comment (pohly) [reply cmd/pmem-csi-driver/main.go]: Let's always keep the source code as simple as possible in cases where runtime overhead isn't relevant (which is almost always the case).

**Comment by okartau** [comment]
uses  ioutil.WriteFile now and does not write term.msg if env.var not defined.
Is use of termination message such API that we need to document it?
It may appear not obvious that undefined env.var causes missing termination cause,
instead of writing it to default location.

**Comment by okartau** [comment]
not tested yet with newest changes

**Comment by pohly** [comment]
Some further improvements are possible:
- The error message is mixed case and misses a space: `Message:      Failed to initialize driver:Invalid driver mode: nodexxx` - Go recommendation is to always write error message in lowercase, to allow concatenating them. This is a problem in several of the PMEM-CSI error messages. The missing space is from the new code.
- pmem-vgm and pmem-ns-init would also benefit from recording the final error message.

As I need to touch the code anyway as part of my PR #252 due to conflicts, I'll make these changes there.
