### PR TITLE
WIP: Add mutex lock around device-oriented operations

### LINKED ISSUE #205: Attempt to create two volumes crashes driver
There is no mutex protecting CreateVolume in Node, leading to crash if deployment tries to create two volumes instead of one (one volume requested in current deploy example).
I experimented with 2 volumes in my-csi-app. I doubled volumes in storageclass and pvc, and mounts in app. The result is that two CreateVolume request are sent to same Node in parallel, and two threads run nodeControllerServer.CreateVolume at same time, and one of threads will crash in
```
signal SIGSEGV: segmentation violation code=0x1 addr=0x3c pc=0x7fcaca6cb770]

runtime stack:
runtime.throw(0x98a841, 0x2a)
        /usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 48 [syscall]:
runtime.cgocall(0x84c050, 0xc0000e1578, 0x0)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc0000e1548 sp=0xc0000e1510 pc=0x40816e
github.com/intel/pmem-csi/pkg/ndctl._Cfunc_ndctl_namespace_get_id(0x0, 0x0)
        _cgo_gotypes.go:718 +0x49 fp=0xc0000e1578 sp=0xc0000e1548 pc=0x811b09
github.com/intel/pmem-csi/pkg/ndctl.(*Namespace).ID.func1(0x0, 0x0)
        /go/src/github.com/intel/pmem-csi/pkg/ndctl/namespace.go:84 +0x56 fp=0xc0000e15b0 sp=0xc0000e1578 pc=0x81ace6
github.com/intel/pmem-csi/pkg/ndctl.(*Namespace).ID(0x0, 0xc000409d20)
        /go/src/github.com/intel/pmem-csi/pkg/ndctl/namespace.go:84 +0x2b fp=0xc0000e15d0 sp=0xc0000e15b0 pc=0x814b4b
github.com/intel/pmem-csi/pkg/ndctl.(*Namespace).MarshalJSON(0x0, 0xc00018a3f0, 0x24, 0x280000000, 0x0, 0x40000000)
        /go/src/github.com/intel/pmem-csi/pkg/ndctl/namespace.go:334 +0x40 fp=0xc0000e16a8 sp=0xc0000e15d0 pc=0x816050
github.com/intel/pmem-csi/pkg/pmem-device-manager.(*pmemNdctl).CreateDevice(0xc00000e0c8, 0xc00018a3f0, 0x24, 0x200000000, 0x973939, 0x5, 0x0, 0x0)
        /go/src/github.com/intel/pmem-csi/pkg/pmem-device-manager/pmd-ndctl.go:92 +0x160 fp=0xc0000e1820 sp=0xc0000e16a8 pc=0x836640
github.com/intel/pmem-csi/pkg/pmem-csi-driver.(*nodeControllerServer).CreateVolume(0xc00013cd20, 0xa00580, 0xc00019f320, 0xc0001d49a0, 0xc00013cd20, 0x1, 0x1)
        /go/src/github.com/intel/pmem-csi/pkg/pmem-csi-driver/controllerserver-node.go:134 +0x2db fp=0xc0000e19f8 sp=0xc0000e1820 pc=0x84017b
```

### PR DESCRIPTION
**Pull request by okartau**
When two volumes are requested at once, Creation typically
causes two parallel Creation calls to run, and without
mutex locking we will run into troubles.

Fixes #205

### CODE REVIEW

**Comment by okartau** [comment]
still seeing crash... should mutex be used with single name, as 2nd run uses new name?

**Comment by okartau** [comment]
Turns out, the mutex use added in first attempt here does not solve the problem, as keymutex works separately for key values, and for different volume Names the different mutex locks were used so it did not protect the region from each other as was plan. The problem is we try to re-use idea from original locking code where the idea was to protect against quickly repeating operations concerning same volume. The new problem we face here is, multiple volume request cause same-time device-side operations (which are not thread-safe). So we need to use simple mutex protecting whole device. I will change the code here. The original mutex use I added in first commit, likely is not even needed

**Comment by okartau** [comment]
I changed keymutex lock to simple lock on device manager side. It's straight from Go example, feedback welcome if something else/more/better is needed.
Now it only activates on devicemode direct, this is were problem was faced.
I briefly checked LVM mode and did not hit race problem, but I think safer is to add similar locking there as well.

**Comment by okartau** [comment]
added LVM side locks. lock itself is defined in utils file to make it neutrally located

**Comment by okartau** [comment]
tested in VM-cluster deployment with 2 parallel volumes, both LVM and direct modes

File: pkg/pmem-device-manager/pmd-lvm.go [hunk 1]
```diff
@@ -129,6 +131,8 @@ func (lvm *pmemLvm) CreateDevice(name string, size uint64, nsmode string) error
 }
 
 func (lvm *pmemLvm) DeleteDevice(name string, flush bool) error {
+	devicemutex.Lock()
+	defer devicemutex.Unlock()
```
Comment (avalluri) [inline pkg/pmem-device-manager/pmd-lvm.go]: The locking should be on device `name` I guess. Deleting two different devices parallelly shouldn't be problem.

Comment (okartau) [reply pkg/pmem-device-manager/pmd-lvm.go]: Delete or create tries to change single system in host, also in LVM mode.
I think it adds safety if we avoid change requests from parallel threads at same time.
Introducing another set of locks would make the code more complex,
and there is no perf. requirement to achieve high speeds here, so my idea is to play safe.

File: pkg/pmem-device-manager/pmd-util.go [hunk 2]
```diff
@@ -2,13 +2,16 @@ package pmdmanager
...
 	"fmt"
+	"sync"
 
 	pmemexec "github.com/intel/pmem-csi/pkg/pmem-exec"
 	"k8s.io/klog/glog"
 	"os"
 	"strconv"
 )
 
+var devicemutex = &sync.Mutex{}
```
Comment (pohly) [inline pkg/pmem-device-manager/pmd-util.go]: Please add an explanation what is protected by this mutex, i.e. which operations must be done while holding the mutex.

File: pkg/pmem-device-manager/pmd-lvm.go (hunk 1 above)
Comment (pohly) [reply pkg/pmem-device-manager/pmd-lvm.go]: I agree that it is better to play it safe here.

File: pkg/pmem-device-manager/pmd-util.go (hunk 2 above)
Comment (okartau) [reply pkg/pmem-device-manager/pmd-util.go]: added a comment, force-pushed
