### PR TITLE
operator/test: fix race condition in events handling

### LINKED ISSUE #864: test flake: assignment to nil map in operator deployment
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/organizations/jenkins/pmem-csi/detail/PR-860/6/pipeline

```
[2021-01-23T02:00:22.076Z] Jan 23 02:00:21.862: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
[2021-01-23T02:00:22.076Z] panic: assignment to entry in nil map
[2021-01-23T02:00:22.076Z] 
[2021-01-23T02:00:22.076Z] goroutine 1756272 [running]:
[2021-01-23T02:00:22.076Z] github.com/intel/pmem-csi/test/e2e/operator.glob..func2.1.1(0xc0007cc080, 0xc0000b90f8)
[2021-01-23T02:00:22.076Z] 	/mnt/workspace/pmem-csi_PR-860/test/e2e/operator/deployment_api.go:106 +0x20b
[2021-01-23T02:00:22.076Z] created by github.com/intel/pmem-csi/test/e2e/operator.glob..func2.1
[2021-01-23T02:00:22.076Z] 	/mnt/workspace/pmem-csi_PR-860/test/e2e/operator/deployment_api.go:99 +0x873
[2021-01-23T02:00:22.076Z] FAIL	github.com/intel/pmem-csi/test/e2e	14455.988s
```

I suspect that this is a race between

https://github.com/intel/pmem-csi/blob/e521220167b19164fea60d1f9f4b10dbe2ce599f/test/e2e/operator/deployment_api.go#L106

and

https://github.com/intel/pmem-csi/blob/e521220167b19164fea60d1f9f4b10dbe2ce599f/test/e2e/operator/deployment_api.go#L120

### PR DESCRIPTION
**Pull request by avalluri**
There is a possible race condition on 'evWatcher' map between
accessing/updating map elements and the map deletion:

```
[2021-01-23T02:00:22.076Z] Jan 23 02:00:21.862: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
[2021-01-23T02:00:22.076Z] panic: assignment to entry in nil map
[2021-01-23T02:00:22.076Z]
[2021-01-23T02:00:22.076Z] goroutine 1756272 [running]:
[2021-01-23T02:00:22.076Z] github.com/intel/pmem-csi/test/e2e/operator.glob..func2.1.1(0xc0007cc080, 0xc0000b90f8)
[2021-01-23T02:00:22.076Z] 	/mnt/workspace/pmem-csi_PR-860/test/e2e/operator/deployment_api.go:106 +0x20b
[2021-01-23T02:00:22.076Z] created by github.com/intel/pmem-csi/test/e2e/operator.glob..func2.1
[2021-01-23T02:00:22.076Z] 	/mnt/workspace/pmem-csi_PR-860/test/e2e/operator/deployment_api.go:99 +0x873
[2021-01-23T02:00:22.076Z] FAIL	github.com/intel/pmem-csi/test/e2e	14455.988s# Please enter the commit message for your changes. Lines starting
```

This could be prevented by mutex locking.

FIXES #864

### CODE REVIEW

File: test/e2e/operator/deployment_api.go [hunk 1]
```diff
@@ -117,6 +125,8 @@ var _ = deploy.DescribeForSome("API", func(d *deploy.Deployment) bool {
 
 	AfterEach(func() {
 		evWatcher.Stop()
+		evMutex.Lock()
+		defer evMutex.Unlock()
```
Comment (pohly) [inline test/e2e/operator/deployment_api.go:129]: Consider the following execution sequence:
- AfterEach is reached, locks mutex and deletes the map, then returns, which unlocks the mutex.
- The goroutine handles an event, creates a goroutine for it, which then assigns to a nil map.

Have you considered my proposal in the issue to wait for the goroutine termination before deleting the map?

File: test/e2e/operator/deployment_api.go [hunk 2]
```diff
@@ -96,16 +98,22 @@ var _ = deploy.DescribeForSome("API", func(d *deploy.Deployment) bool {
...
 			for watchEvent := range evWatcher.ResultChan() {
 				ev, ok := watchEvent.Object.(*corev1.Event)
 				if !ok || ev.Source.Component != "pmem-csi-operator" {
 					continue
 				}
-				if _, ok := evCaptured[ev.InvolvedObject.UID]; !ok {
-					evCaptured[ev.InvolvedObject.UID] = map[string]struct{}{}
-				}
-				evCaptured[ev.InvolvedObject.UID][ev.Reason] = struct{}{}
+				go func() {
```
Comment (pohly) [inline test/e2e/operator/deployment_api.go:108]: Why a goroutine here?

If you want to lock the mutex and unlock when done, then just wrap the map access with Lock/Unlock:
```
   evMutex.Lock()
   if _, ok := evCaptured[ev.InvolvedObject.UID]; !ok {
   ...
   }
   evMutex.Unlock()
```

But I doubt that this is actually solving anything, see my other comment.

    evMutex.Lock()

Comment (pohly) [reply test/e2e/operator/deployment_api.go:108]: `defer` is only useful when there are multiple return points. This map usage is so simple that we don't need it.

File: test/e2e/operator/deployment_api.go (hunk 1 above)
Comment (avalluri) [reply test/e2e/operator/deployment_api.go]: > Consider the following execution sequence:
> 
> * AfterEach is reached, locks mutex and deletes the map, then returns, which unlocks the mutex.
> * The goroutine handles an event, creates a goroutine for it, which then assigns to a nil map.
> 
Yes, I agree. there case still possible.

> Have you considered my proposal in the issue to wait for the goroutine termination before deleting the map?

Pushed new changes with  this.

File: test/e2e/operator/deployment_api.go [hunk 3]
```diff
@@ -97,6 +99,8 @@ var _ = deploy.DescribeForSome("API", func(d *deploy.Deployment) bool {
 		Expect(err).ShouldNot(HaveOccurred(), "get events watcher")
 		evCaptured = map[types.UID]map[string]struct{}{}
 		go func() {
+			evWait.Add(1)
+			defer evWait.Done()
```
Comment (pohly) [inline test/e2e/operator/deployment_api.go:103]: Still slightly broken. The `evWait.Add(1)` has to be outside of the goroutine. 

Otherwise we get:
- goroutine created, but not started yet
- AfterEach is called, `evWait.Wait()` returns immediately, map becomes nil
- goroutine starts to run, processes events, panics

**Review by pohly — CHANGES_REQUESTED** [review]

**Review by pohly — APPROVED** [review]
